### ISSUE TITLE
How to increase FPS

### ISSUE THREAD

**Issue by anhle-uet** [megvii-model/MOTR#13]
I ran MOTR on K80 with input of size 720×1280. But the tracking FPS seems kinda low ~1 FPS. Is there any way around to increase the FPS?

**Comment by dbofseuofhust** [comment]
> I ran MOTR on K80 with input of size 720×1280. But the tracking FPS seems kinda low ~1 FPS. Is there any way around to increase the FPS?

Thanks for your attention! the low FPS is caused by memory bank, especially when there are >40 objects per image. We suggest to disenabled memory bank or reduce save_period (https://github.com/megvii-model/MOTR/blob/main/models/memory_bank.py#L24) to get trade off bwteen performance and speed. The performance won't drop a lot.
