### ISSUE TITLE
Demo with init boxes

### ISSUE THREAD

**Issue by gurkirt** [megvii-model/MOTR#21]
Hello, Thank you for this amazing work. 

Is it possible for your method to accept bounding box initialisation?

**Comment by TerranLord** [comment]
MOTR is not designed with bbox initialzation. 
If you really need that, personally, I think you can follow the Deformable-DETR with Two-stage setting where bboxes outputted by the first stage are mapped into queries for the second stage(transformer decoder).  Specifically, once you would like use init bboxes rather than model detection, you can replace the learnable queries(the detection queries of length 300, used to detect new-born object) by the queries mapped from your init bboxes. 

In this way, MOTR could take your init bboxes rather than bboxes detected by itself as new-born objects while keep the tracking mechanism almost unchanged.

However, you should re-train MOTR to receive queries converted from init bboxes. And the label assignment strategy should be also carefully and correspondingly changed. For example, a GT object is fully missed in your init bboxes, but the one-to-one matching still requires a dt box assigned to this missed GT, casuing the learning of network difficult.
