### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by sfwang20** [megvii-model/MOTR#26]
Thanks for your work.

How can we train this project on a custom dataset? 
Is there a generate_labels files or any steps to prepare the data for training purposes?

Thank you.

**Comment by dbofseuofhust** [comment]
> Thanks for your work.
> 
> How can we train this project on a custom dataset? Is there a generate_labels files or any steps to prepare the data for training purposes?
> 
> Thank you.

Thanks for attention!
You can convert your custom dataset by the following steps:
1) dump detection results for each video into one txt file (e.g gt.txt) with format:
`<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, -1, -1, -1`
2) run this [script ](https://github.com/megvii-model/MOTR/blob/main/datasets/data_path/gen_labels_16.py) to generate the format for MOTR.
3) generate train/val splits using this [script ](https://github.com/megvii-model/MOTR/blob/main/datasets/data_path/prepare.py).

**Comment by abdallah1989203** [comment]
@dbofseuofhust Can you explain Step 3? Unfortunately, it didn't work for me... In Step 2, I also inserted a code snippet into gen_labels_15.py between lines 42 and 43:

```
42 gt = np.loadtxt(gt_txt, dtype=np.float64, delimiter=',')
43 for fid, tid, x, y, w, h, mark, _, _, _ in gt:
```

```
If gt.shape[1] < 10:
missing_values = 10 - gt.shape[1]
gt = np.pad(gt, ((0, 0), (0, missing_values)), mode='constant', constant_values=0)

idx = np.lexsort(gt.T[:2, :])
gt = gt[idx, :]

seq_label_root = osp.join(label_root, seq, 'img1')
mkdirs(seq_label_root)
```

I encountered an error indicating that I have only 9 inputs instead of the expected 10. My dataset looks like this:
/data/vid1/gt and img1, for vid1, ..., vidx
Example of a gt.txt file:
19,1,1292.93,4.09,46.069999999999936,35.510000000000005,1,1,1.0
The data format is MOT 1.1, and I labeled the data in CVAT and exported it as MOT 1.1.

How can I prepare my dataset for training a model? It would be really kind and helpful if you could assist me. Thank you in advance!

**Comment by dbofseuofhust** [comment]
The really useful variables are the first seven parameters and it seems your data format is (fid, tid, x, y, w, h, mark, _, _), so just change it into:&nbsp;for fid, tid, x, y, w, h, mark, _, _ in gt
you can refer this file https://github.com/megvii-research/MOTR/blob/main/datasets/data_path/gen_labels_16.py





杏雨难寻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/MOTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 晚上9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/MOTR] Train on custom dataset (Issue #26)





 
@dbofseuofhust Can you explain Step 3? Unfortunately, it didn't work for me... In Step 2, I also inserted a code snippet into gen_labels_15.py between lines 42 and 43:
 42 gt = np.loadtxt(gt_txt, dtype=np.float64, delimiter=',') 43 for fid, tid, x, y, w, h, mark, _, _, _ in gt:  If gt.shape[1] < 10: missing_values = 10 - gt.shape[1] gt = np.pad(gt, ((0, 0), (0, missing_values)), mode='constant', constant_values=0) idx = np.lexsort(gt.T[:2, :]) gt = gt[idx, :] seq_label_root = osp.join(label_root, seq, 'img1') mkdirs(seq_label_root)  
I encountered an error indicating that I have only 9 inputs instead of the expected 10. My dataset looks like this:
 /data/vid1/gt and img1, for vid1, ..., vidx
 Example of a gt.txt file:
 19,1,1292.93,4.09,46.069999999999936,35.510000000000005,1,1,1.0
 The data format is MOT 1.1, and I labeled the data in CVAT and exported it as MOT 1.1.
 
How can I prepare my dataset for training a model? It would be really kind and helpful if you could assist me. Thank you in advance!

**Comment by abdallah1989203** [comment]
@dbofseuofhust But I don't have any 'seqinfo.ini' files, how can I solve this problem?

**Comment by dbofseuofhust** [comment]
just remove those lines:
seq_info = open(osp.join(seq_root, seq, 'seqinfo.ini')).read()
seq_width = int(seq_info[seq_info.find('imWidth=') + 8:seq_info.find('\nimHeight')])&nbsp;seq_height = int(seq_info[seq_info.find('imHeight=') + 9:seq_info.find('\nimExt')])


and replace&nbsp;seq_width&nbsp;with your own image with such as 1333 and replace&nbsp;seq_height&nbsp;with your own image height such as 800&nbsp;
 



    





杏雨难寻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/MOTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月6日(星期四) 凌晨5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/MOTR] Train on custom dataset (Issue #26)





 
@dbofseuofhust But I don't have any 'seqinfo.ini' files, how can I solve this problem?

**Comment by abdallah1989203** [comment]
@dbofseuofhust Thank you very much for your effort! However, I still have some questions. Regarding the statement "3.generate train/val splits using this script," I noticed that the prepare.py script only generated a single TXT file containing all frames with their corresponding TXT files. Could you please clarify what you mean by "splits" in this context?

**Comment by abdallah1989203** [comment]
@dbofseuofhust Thank you very much for your effort! However, I still have some questions. Regarding the statement "3.generate train/val splits using this script," I noticed that the prepare.py script only generated a single TXT file containing all frames with their corresponding TXT files. Could you please clarify what you mean by "splits" in this context?
2. I have videos as images in a dataset, and bounding boxes (bbox) are not present in all frames. Should I train the model only on the frames that have a bounding box and delete the empty frames?

**Comment by abdallah1989203** [comment]
@dbofseuofhust 
I have write a new method for my dataset:
```
def solve_custom_dataset(root):
    dataset_path = '/data/MOTR/motr'
    data_root = os.path.join(root, dataset_path)
    video_folders = [folder for folder in os.listdir(data_root) if os.path.isdir(os.path.join(data_root, folder))]

    frames = []
    for video_folder in video_folders:
        img_folder = os.path.join(data_root, video_folder, 'img1')
        gt_file = os.path.join(data_root, video_folder, 'gt', 'gt.txt')
        if os.path.exists(img_folder) and os.path.exists(gt_file):
            with open(gt_file, 'r') as f:
                for line in f:
                    frame_path = os.path.join(dataset_path, video_folder, 'img1', line.split(',')[0] + '.PNG')
                    frames.append(frame_path)
    return frames
```
I have just a frame.txt where there is all frames.
so can you me say please if that is true or false?
and what should change in the file r50_motr_train.sh or in main.py?

**Comment by abdallah1989203** [comment]
@dbofseuofhust please answer me when you have Time! Thx.
